language: node_js
node_js:
  - '12.18.4'

addons:
  sauce_connect: true

install:
  - npm install

cache:
  directories:
    - node_modules
    - e2e/helpers/client/client_secret.json
    - e2e/*.json
    - pixDiff/*

script:
  # to download binaries
  #- npm run wd-update

  # run unit tests
  - npm test
