language: node_js
node_js:
  - '9.5.0'

addons:
  sauce_connect: true

notifications:
  email:
    recipients:
      - angie@gapminder.org
      - abidrana7@gmail.com
    on_success: change
    on_failure: always

  slack:
    rooms:
      - gapminder:siB4Z9ymsYR6qHnRPpgUoB2Q#vizabi-spam
    on_success: change
    on_failure: always

cache:
  directories:
    - node_modules
    - e2e/helpers/client_secret.json
    - e2e/helpers/list.json

#install:
 # - npm install

#script:
  # to download binaries
  #- npm run wd-update

  # applitools batch name
  # - export APPLITOOLS_BATCH_ID=`${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`

  # run unit tests
  #- npm test
