language: node_js
node_js:
  - '9.5.0'

addons:
  sauce_connect:
    username: "gapminder"
  jwt:
    secure: "The secure string output by `travis encrypt SAUCE_ACCESS_KEY=6a9bed19-2742-4df7-9d2a-7b3fa420d37a`"

notifications:
  email:
    recipients:
      - abidrana7@gmail.com
    on_success: change
    on_failure: always

  #slack:
    #rooms:
      #- gapminder:siB4Z9ymsYR6qHnRPpgUoB2Q#vizabi-spam
    #on_success: change
    #on_failure: always

cache:
  directories:
    - node_modules
    - e2e/helpers/client_secret.json

install:
  - npm install

script:
  # to download binaries
  #- npm run wd-update

  # run unit tests
  - npm test
