language: node_js
node_js:
  - '12.18.4'

#addons:
  #sauce_connect: true

notifications:
  email:
    recipients:
      - angie@gapminder.org

    on_success: change
    on_failure: always

  slack:
    rooms:
      - gapminder:siB4Z9ymsYR6qHnRPpgUoB2Q#vizabi-spam
    on_success: change
    on_failure: always

install:
  - npm install

cache:
  directories:
    - node_modules
    - "./e2e/testData.json"
    - "./pixDiff/baseline/"

script:
  # to download binaries
  #- npm run wd-update

  # to overcome 'no such file or directory, scandir travis ci'
  - npm rebuild node-sass

  # run tests
  - npm test
