name: Percy manual ALL SUITES

on:
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  percy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite: [tools-page,dollar-street,gapminder-org]
        include:
        - suite: tools-page
          token: PERCY_TOKEN_TOOLS_PAGE
        - suite: dollar-street
          token: PERCY_TOKEN_DOLLAR_STREET
        - suite: gapminder-org
          token: PERCY_TOKEN_GAPMINDER_ORG
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.16.0
          cache: 'npm'
      - name: npm install
        env:
          CHROME_VERSION: "110.0.5481.77-1"
        run: |
          npm install
          npm run wd-update
          mkdir pixDiff && mkdir pixDiff/diff && mkdir pixDiff/baseline
          wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb"
          sudo dpkg -i "google-chrome-stable_${CHROME_VERSION}_amd64.deb"
      - name: VISUAL TESTS FOR ${{ matrix.suite }}
        env: 
          PERCY_TOKEN: ${{ secrets[matrix.token] }}
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}    
          PERCY_BRANCH: manual     
          PERCY_TARGET_BRANCH: prod
        run: npm run percy:${{ matrix.suite }}
